replace_list = {
    'ok':'tốt','ô kêi': 'tốt', 'okie': 'tốt', 'o kê': 'tốt', 'okey': 'tốt', 'ôkê': 'tốt', 'oki': 'tốt', 'oke': 'tốt', 'okay': 'tốt', 'okê': 'tốt','okr':'tốt',
    'tks': 'cảm ơn', 'thks': 'cảm ơn', 'thanks': 'cảm ơn', 'ths': 'cảm ơn', 'thank': 'cảm ơn',
    'kg': 'không', 'not': 'không', 'k': 'không', 'kh': 'không', 'kô': 'không', 'hok': 'không', 'ko': 'không', 'khong': 'không', 'kp': 'không phải',
    'he he': 'tích cực', 'hehe': 'tích cực', 'hihi': 'tích cực', 'haha': 'tích cực', 'hjhj': 'tích cực', 'thick': 'tích cực',
    'cc': 'tiêu cực', 'huhu': 'tiêu cực', 'cute': 'dễ thương', 'cũng không quá': 'bình thường', 'không hẳn': 'bình thường', 'tạm được': 'bình thường',
    'sz': 'cỡ', 'size': 'cỡ', 'dm':'tiêu cực','dme':'tiêu cực','ditme':'tiêu cực', 'tạm ổn': 'bình thường',
    'wa': 'quá', 'wá': 'quá', 'qá': 'quá', 'cx':'cũng','lác': 'tệ','không quá tốt': 'bình thường',
    'đx': 'được', 'dk': 'được', 'dc': 'được', 'đk': 'được', 'đc': 'được',
    'vs': 'với', 'j': 'gì', '“': ' ', 'time': 'thời gian', 'm': 'mình', 'mik': 'mình', 'r': 'rồi', 'bjo': 'bao giờ', 'very': 'rất',
    'authentic': 'chuẩn chính hãng', 'aut': 'chuẩn chính hãng', 'auth': 'chuẩn chính hãng', 'date': 'hạn sử dụng', 'hsd': 'hạn sử dụng',
    'store': 'cửa hàng', 'sop': 'cửa hàng', 'shopE': 'cửa hàng', 'shop': 'cửa hàng','hk': 'không','cammera': 'camera', 'came': 'camera','chíp':'chip',
    'sp': 'sản phẩm', 'product': 'sản phẩm', 'hàg': 'hàng', 'cc': 'tệ', 'dm': 'tệ',
    'ship': 'giao hàng', 'delivery': 'giao hàng', 'síp': 'giao hàng', 'order': 'đặt hàng', 'load':'tải','4g': 'mạng viễn thông',
    '3g': 'mạng viễn thông','ram':'vi xử lí','rom':'vi xử lí', 'hard disk': 'ổ cứng',
    'feat': 'tính năng', 'update': 'nâng cấp', 'smart phone': 'điện thoại', 'smartphone': 'điện thoại',
    'gud': 'tốt', 'wel': 'tốt', 'good': 'tốt', 'gút': 'tốt', 'tot': 'tốt', 'nice': 'tốt', 'perfect': 'rất tốt',
    'quality': 'chất lượng', 'chất lg': 'chất lượng', 'chat': 'chất', 'excelent': 'hoàn hảo', 'bt': 'bình thường',
    'sad': 'tệ', 'por': 'tệ', 'poor': 'tệ', 'bad': 'tệ','pk':'biết','bl': 'bình luận', 'cmt': 'bình luận','mn':'mọi người',
    'beautiful': 'đẹp tuyệt vời', 'dep': 'đẹp', 'chs': 'chơi', 'rât': 'rất','thất':'thất',
    'xau': 'xấu', 'sấu': 'xấu', 'ncl': 'nói chung là','tkj': 'thì', 'nưa': 'nữa',
    'thik': 'thích', 'iu': 'yêu', 'fake': 'giả mạo', 'wep': 'web','mí': 'mới','dluong': 'dung lượng',
    'quickly': 'nhanh', 'quick': 'nhanh', 'fast': 'nhanh', 'rqats':'rất','trc': 'trước',
    'fresh': 'tươi', 'delicious': 'ngon',
    'wf': 'wifi', 'ôk': 'tốt','đt': 'điện thoại', 'cam': 'camera', 'maxloa': 'âm thanh to',
    'ctkm': 'chương trình khuyến mãi', 'TGDD': 'thế giới di động', 'zìa': 'về',
    'rraats': 'rất', 'mk' : 'mật khẩu', 'vn' : 'việt nam', 'noi':'nói', 'la':'là', 'qtrinh':'quá trình', 'sd':'sử dụng',
    'ms':'mới', 'vd':'ví dụ', 'lag':'tệ','call':'gọi', 'hên':'tốt', 'tậu':'mua', 'loạn':'tệ', 'đơ':'tệ','dag':'đang',
    'ảo': 'tệ','tgdd': 'thế giới di động',

    'ks': 'khách sạn', 'nv': 'nhân viên',
    'nt': 'nhắn tin', 'ib': 'nhắn tin', 'tl': 'trả lời', 'trl': 'trả lời', 'rep': 'trả lời',
    'fback': 'feedback', 'fedback': 'feedback',' như cc': 'tệ', 'cùi': 'tệ', 'không bằng': 'tệ',
    'sd': 'sử dụng', 'sài': 'xài', 'dỏm':'tệ', 'xạc': 'sạc',
    '^_^': 'tích cực', ':)': 'tiêu cực', ':(': 'tiêu cực',
    'beautiful':' đẹp tuyệt vời ','r': ' rồi ','order':' đặt hàng ',
    'lg': 'lượng', 'sd': ' sử dụng ','dt': 'điện thoại',
    'fb': ' facebook ', 'face': ' facebook ', 'very': ' rất ','quả ng':' quảng  ',
    'qủa': ' quả ','bk':'biết', 'dthoai':'điện thoại','thegioididong':'thế giới di động', 'đt': 'điện thoại',
    'zin':'tích cực','hazzz': 'tiêu cực','test': 'thử','bit': 'biết', 'ak':'à','noiz':'nói','rats':'rất','j':'gì','dis':'tiêu cực',
    'phên': 'tích cực','kog': 'không', 'mia': 'mua', 'ja':'giá','way':'quay', 'zay':'vậy'}
